version: '3'

volumes:
  data-volume:
  desafio-cnab-data:
    driver: local

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: desafio-cnab
    volumes:
      - desafio-cnab-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root@cnab@01
      - MYSQL_DATABASE=cnab
      - MYSQL_USER=user_cnab
      - MYSQL_PASSWORD=EPcUUKctcJp0k33Pa